apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: vault
  name: vault
  namespace: default
data:
  config.hcl: |
      backend "mysql" {
       address = "${MYSQL_ENDPOINT}:3306"
       username = "${MYSQL_USERNAME}"
       password = "${MYSQL_PASSWORD}"
      }
      listener "tcp" {
       address = "0.0.0.0:8200"
       tls_disable = 1
       tls_cert_file = "/etc/tls/vault-crt.pem"
       tls_key_file = "/etc/tls/vault-key.pem"
      }
      disable_mlock = true