apiVersion: apps/v1
kind: Deployment
metadata:
  name: vamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vamp
  template:
    metadata:
      labels:
        app: vamp
      name: vamp
    spec:
      containers:
      - name: vamp
        image: magneticio/vamp-ee:${VAMP_IMAGE}
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: VAMP_EE_NAMESPACE
          value: vampio
        - name: VAMP_EE_METADATA_NAMESPACE_TITLE
          value: vamp.io
        - name: VAMP_PERSISTENCE_KEY_VALUE_STORE_TYPE
          value: vault
        - name: VAMP_PERSISTENCE_KEY_VALUE_STORE_VAULT_URL
          value: http://vault.default.svc.cluster.local:8200
        - name: VAMP_PERSISTENCE_KEY_VALUE_STORE_BASE_PATH
          value: secret/vamp
        - name: VAMP_PERSISTENCE_KEY_VALUE_STORE_VAULT_TOKEN
          value: vamp
        - name: VAMP_WORKFLOW_DRIVER_WORKFLOW_VAMP_KEY_VALUE_STORE_TOKEN
          value: vamp
        - name: VAMP_WORKFLOW_DRIVER_WORKFLOW_VAMP_KEY_VALUE_STORE_CONNECTION
          value: http://vault.default.svc.cluster.local:8200
        resources:
          requests:
            cpu: 0.2
            memory: 2048
        securityContext:
          privileged: false
      imagePullSecrets:
        - name: regsecret
        
        
