# Allow VAMP user to create resources in the namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vamp
subjects:
- kind: User
  name: vamp-ci
  # namespace: default (possible to limit access to namespaces)
roleRef:
  kind: ClusterRole
  name: vamp 
  apiGroup: rbac.authorization.k8s.io