kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vamp
  # namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  - replicationcontrollers
  - statefulsets
  - daemonsets
  verbs: ["get", "list", "watch"]